apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-app
  labels:
    app: container-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-app
  template:
    metadata:
      labels:
        app: container-app
    spec:
      containers:
      - name: container-app
        image: gcr.io/eighth-codex-439113-s2/container-app:latest
        ports:
        - containerPort: 80