apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: microfrontends-gateway
  namespace: sumanns
  annotations:
    networking.gke.io/static-ip: "35.225.249.245"  # Ensure this IP is reserved in GCP
spec:
  gatewayClassName: gke-l7-global-external-managed  # Ensure this GatewayClass exists
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All  # Allow routes from all namespaces
      hostname: "*.sumangcodes.info"  # Wildcard for subdomains
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sumangcodes-info-cert  # Secret with TLS certs
      allowedRoutes:
        namespaces:
          from: All  # Allow HTTPS routes from all namespaces
