apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: sumanns
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All