apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  namespace: sumanns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: gcr.io/eighth-codex-439113-s2/shopping-cart:latest
          ports:
            - containerPort: 3002  # Same as the exposed port in the Dockerfile
          readinessProbe:
            httpGet:
              path: /ready  # Ensure your app has this health endpoint
              port: 3002     # Probe using the correct port
            initialDelaySeconds: 10  # Wait before the first probe
            periodSeconds: 10        # Frequency of probes
          livenessProbe:
            httpGet:
              path: /health  # Same endpoint for liveness check
              port: 3002
            initialDelaySeconds: 30  # Delay for the first liveness check
            periodSeconds: 10        # Frequency of checks